<?php
// add_action( 'pre_get_posts', 'adjust_current_presentations_slides' );
function adjust_current_presentations_slides( $query ) {
	// Do nothing if not on Fundraiser page
	// if( ! is_page( 'Fundraiser' ) ) {
	// return;
	// }
	// Make sure we're talking to the WP_Query
	// generated by the Recent Posts widget
	if ( ! is_main_query() &&
		$query->query['no_found_rows'] === true &&
		$query->query['post_type'] === null
	) {

		// Fetch only posts tagged with "fundraiser"
		$taxquery = array(
			array(
				'taxonomy' => 'reveal_slides_cat',
				// 'field' => 'slug',
				'terms' => array( 'wclvpa19' ),
			),
		);
		$query->set( 'tax_query', $taxquery );
	}
}
// add_action( 'init', 'change_reveal_slides_cat_label', 11 );
/**
 * Let's rename the native taxonomy Categories to Presentations.
 * This function takes care of the Taxonomy labels.
 *
 * [change_reveal_slides_cat_label]
 *
 * @return [type] [description]
 */
function change_reveal_slides_cat_label() {
	global $wp_taxonomies;
	$section = $wp_taxonomies['reveal_slides_cat'];
	// $section->meta_box_cb = 'wp_dropdown_categories';
	$labels                     = &$wp_taxonomies['reveal_slides_cat']->labels;
	$labels->name               = 'Presentation';
	$labels->singular_name      = 'Presentation';
	$labels->add_new            = 'Add Presentation';
	$labels->add_new_item       = 'Add Presentation';
	$labels->edit_item          = 'Edit Presentation';
	$labels->parent_item        = 'Parent Presentation';
	$labels->parent_item_colon  = 'Parent Presentation:';
	$labels->new_item           = 'Presentation';
	$labels->view_item          = 'View Presentation';
	$labels->search_items       = 'Search Presentations';
	$labels->not_found          = 'No Presentations found';
	$labels->not_found_in_trash = 'No Presentations found in Trash';
	$labels->all_items          = 'All Presentations';
	$labels->menu_name          = 'Presentation';
	$labels->name_admin_bar     = 'Presentation';
}
